spring:
  datasource:
    url: jdbc:sqlite:data/bot_database.sqlite3
    driver-class-name: org.sqlite.JDBC
    username: deadly
    password: disappointed

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
